### ISSUE TITLE
Adding to the "Get involved" page -instructions for blog / event posts

### ISSUE THREAD

**Issue by mcragin** [go-fair-us/go-fair-us.github.io#11]
Here are bullets to add for the Get Involved  / Posts instructions page:

- Posts to this website should include a paragraph on the relevance to the US GO FAIR organization and/or goals. Please try to address the following questions as part of your post or announcement:
     - What is the benefit or contribution to FAIR capacity in the U.S. (or geographic location)?
     - How does this address “Change, Train, or Build?”
     - Describe the role or relationship of this effort to US GO FAIR  - specifically, how does being connected to GO FAIR US help this event, activity, or effort? (e.g. broaden reach, support main aims, provide in-kind support, etc.)

**Comment by libcce** [comment]
Thanks @mcragin it has been updated:
https://github.com/go-fair-us/go-fair-us.github.io/blob/master/_drafts/contributing-instructions.md
